Example scitoken plugin - calls out to a shell script
glideinWMS/glideinwms pull request #100
Opened 2022-03-18 19:07 UTC by rynge

2022-03-23 16:06 UTC, mambelli requested changes

2022-03-26 01:59 UTC, rynge commented on plugins/scitokens_callout.py
> +
Done

2022-03-26 01:59 UTC, rynge commented on plugins/scitokens_callout.py
> +    tkn_file = tkn_dir + "/" + group + "." + entry["name"] + ".scitoken"
Done

2022-03-26 02:00 UTC, rynge commented on plugins/scitokens_callout.py
> +            tkn_age = time.time() - os.stat(tkn_file).st_mtime
Done. Where would the file be copied?

2022-03-26 02:00 UTC, rynge commented on plugins/scitokens_callout.py
> +
It is an example plugin - I don't think we should over-complicate it

2022-03-28 19:58 UTC, mambelli commented on plugins/scitokens_callout.py
> +            tkn_age = time.time() - os.stat(tkn_file).st_mtime
Since the script invoked is not known I thought it could copy over files maintained in some other directory. Maybe I'm overthinking.

2022-03-28 19:58 UTC, mambelli approved these changes

2022-03-28 19:59 UTC, merged