Integrate changes to support credential generators
glideinWMS/glideinwms pull request #108
Opened 2022-03-31 16:11 UTC by BrunoCoimbra

This pull request integrates the resulting code of the GWMS hackathon on March 18th.

I made improvements to the handling of credential plugins on the frontend main loop, and a couple of small fixes to the scitoken_callout plugin. I also changed our spec file to install plugins under the `plugins` directory at `/etc/gwms-frontend/plugin.d`.

2022-04-14 21:55 UTC, namrathaurs requested changes
Left a few comments as part of my review although not sure if they are really applicable. Since the patch resulting from the hackathon is relatively new to me, it might also be nice if @ddbox or @mmascher can do a quick review (those files that have major changes) to make sure I haven't missed anything important to raise.

2022-04-14 21:55 UTC, namrathaurs commented on frontend/glideinFrontendElement.py
> +                logSupport.log.debug("found scitoken %s" % scitoken_fullpath)
I see that logSupport is being used here to print the string. Does f-string formatting apply here like how we use it in python 3.x?

2022-04-14 21:55 UTC, namrathaurs commented on frontend/glideinFrontendElement.py
> +                logSupport.log.exception("failed to read scitoken: %s" % err)
same comment as previous

2022-04-14 21:55 UTC, namrathaurs commented on frontend/glideinFrontendElement.py
> +                    logSupport.log.debug("found credential generator plugin %s" % generator)
same comment as previous

2022-04-14 21:55 UTC, namrathaurs commented on frontend/glideinFrontendElement.py
> +                        logSupport.log.warning("Failed to load credential generator plugin %s" % generator)
same comment as previous

2022-04-14 21:55 UTC, namrathaurs commented on frontend/glideinFrontendElement.py
> +                        logSupport.log.warning("Failed to generate credential: %s." % e)
same comment as previous

2022-04-14 21:55 UTC, namrathaurs commented on plugins/scitokens_callout.py
> +        subject = "vofrontend-%s" % (entry["name"])
is f-string formatting possible here?

2022-04-14 21:55 UTC, namrathaurs commented on plugins/scitokens_callout.py
> +    tkn_dir = "/var/lib/gwms-frontend/tokens.d"
any possibility to avoid the hardcoding?

2022-04-14 21:55 UTC, namrathaurs commented on plugins/scitokens_callout.py
> +            logger.debug("created token %s" % tkn_file)
I see that logger is being used here to print the string. Does f-string formatting apply here like how we use it in python 3.x?

2022-04-14 21:55 UTC, namrathaurs commented on plugins/scitokens_callout.py
> +        logger.log.warning("failed to create %s" % tkn_file)
same comment as previous

2022-04-26 22:06 UTC, mambelli requested changes

2022-04-28 18:07 UTC, BrunoCoimbra commented on frontend/glideinFrontendElement.py
> +                    generator = generators_map[cfname]
This shouldn't be a problem, as earlier in the code, we source the `generators` variable from the `CredentialGenerators` group or frontend config. If no generator is provided, the generators variable is `None` and will abort the function.

Here's the relevant portion of the code:
```python
generators = elementDescript.element_data.get("CredentialGenerators")
trust_domain_data = elementDescript.element_data.get("ProxyTrustDomains")
if not generators:
    generators = elementDescript.frontend_data.get("CredentialGenerators")
if not trust_domain_data:
    trust_domain_data = elementDescript.frontend_data.get("ProxyTrustDomains")
if trust_domain_data and generators:
    ...
```

2022-04-29 21:57 UTC, mambelli approved these changes

2022-04-29 22:01 UTC, merged