ensure any files ending in 'idtoken' are transferred to glidein
glideinWMS/glideinwms pull request #119
Opened 2022-04-15 20:19 UTC by ddbox

credential directory and the correct one of potentially many
is exported as GLIDEIN_CONDOR_TOKEN

2022-04-15 20:34 UTC, mambelli requested changes

2022-04-15 20:34 UTC, mambelli commented on creation/web_base/glidein_startup.sh
>    export GLIDEIN_CONDOR_TOKEN="${tk}"
Since you are using a for you should protect against there being more than one file matching

2022-04-15 20:34 UTC, mambelli commented on creation/web_base/setup_x509.sh
> +        for TOK in ${cred_base}/*.idtoken; do
If GLIDEIN_CONDOR_TOKEN is not defined (old frontend not sending token) also other tokens are not copied

2022-04-20 18:49 UTC, ddbox commented
review suggestions tested and pushed to branch

2022-04-20 20:28 UTC, mambelli approved these changes

2022-04-20 20:28 UTC, merged