Allows token usage in manual_glidein_submit. Fixes #140
glideinWMS/glideinwms pull request #158
Opened 2022-06-20 16:29 UTC by mmascher

2022-06-21 12:54 UTC, mambelli commented
Pylint is failing, did you run pre-commit?

2022-06-21 13:03 UTC, mambelli requested changes

2022-06-21 13:03 UTC, mambelli commented on factory/tools/manual_glidein_submit.py
> +
I think you should have `)` here

2022-06-27 16:55 UTC, mmascher commented
> Pylint is failing, did you run pre-commit?

done now, apologies

2022-06-27 23:06 UTC, mambelli approved these changes

2022-06-27 23:07 UTC, mambelli commented
Pylint was still failing. I added the fix

2022-06-27 23:07 UTC, merged