Fixed default TRUST_DOMAIN to hostname of the first collector without port
glideinWMS/glideinwms pull request #226
Opened 2022-10-18 21:32 UTC by mambelli

Fixed TRUST_DOMAIN handling: now it is the hostname of the first collector (without port) by default (i.e. if TRUST_DOMAIN is not specified in the configuration)

Considering only the first collector in the list (CE collectors could be added to the glidein). Furthermore, secondary collectors could have a different port, so the port should be removed. Same for the synful string.
Both shell script and python code have been updated accordingly

Then fixed condor config vars: TRUST_DOMAIN is a condor expression, not a quoted string (suggested by TJ)

Added also unit tests for setup_x509.sh
And resed SEC_PASSWORD_DIRECTORY to an empty string (not needed in a client)

TODO: evaluate if the entry/credential trust domain from the Frontend configuration should be considered instead of the HTCSS one. Will open an issue for it.

2022-10-21 16:31 UTC, namrathaurs requested changes
Very minor comments upon reviewing. Please check if they are valid, otherwise can be ignored.

2022-10-21 16:31 UTC, namrathaurs commented on creation/web_base/setup_x509.sh
> +            #"$error_gen" -error "setup_x509.sh" "WN_Resource" "$STR1" "directory" "$X509_CERT_DIR"
same comment about replacing the script name with `$0`

2022-10-21 16:31 UTC, namrathaurs commented on creation/web_base/setup_x509.sh
> +        "$error_gen" -error "setup_x509.sh" "WN_Resource" "No valid credential (x509 proxy or idtoken) found"
same comment as previous

2022-10-21 16:31 UTC, namrathaurs commented on creation/web_base/setup_x509.sh
> +    "$error_gen" -ok "setup_x509.sh" "idtoken" "${GLIDEIN_CONDOR_TOKEN:-unavailable}" "trust_domain" "${TRUST_DOMAIN:-unavailable}" "proxy" "${X509_USER_PROXY:-unavailable}" "cert_dir" "${X509_CERT_D
same here

2022-10-22 03:20 UTC, mambelli commented on creation/web_base/setup_x509.sh
> +            "$error_gen" -ok "setup_x509.sh" "idtoken" "${GLIDEIN_CONDOR_TOKEN:-unavailable}" "proxy" "${X509_USER_PROXY:-unavailable}"
done

2022-10-22 03:21 UTC, mambelli commented on creation/web_base/setup_x509.sh
> +    add_config_line_source="$(grep '^ADD_CONFIG_LINE_SOURCE ' "$glidein_config" | cut -d ' ' -f 2-)"
No, gconfig_... are defined only after add_config_line_source is retrieved and sourced

2022-10-22 03:22 UTC, mambelli commented on creation/web_base/setup_x509.sh
> +        "$error_gen" -error "setup_x509.sh" "WN_Resource" "Periodic execution should not reach setup, probably needed glidein_config variables are not set"
No, only if it fails, the if contains an `exit` command

2022-10-26 08:56 UTC, namrathaurs requested changes
Once the comment is addressed, this PR is ready for merging

2022-10-26 08:56 UTC, namrathaurs commented on creation/web_base/setup_x509.sh
> +            #"$error_gen" -error "setup_x509.sh" "WN_Resource" "$STR1" "directory" "$X509_CERT_DIR"
The `setup_x509.sh` in this line might have been forgotten to rename the script to SCRIPT_NAME

2022-10-26 15:08 UTC, mambelli commented
Those were in comments kept around for the error strings, anyway I removed them.

2022-10-26 15:21 UTC, namrathaurs commented
My bad, did not notice closely that the line was commented out. It’s now ready for merging!

2022-10-26 15:30 UTC, merged