Add idtokens to manual_glidein_submit
glideinWMS/glideinwms pull request #284
Opened 2023-04-19 16:23 UTC by mmascher

2023-05-01 17:25 UTC, mambelli requested changes

2023-05-01 17:25 UTC, mambelli commented on CHANGELOG.md
> +-   manual_glidein_submit now correctly sets idtokens in the EncryptedInputFiles (PR #280)
It is `(issue #283)` or `(issue #283, PR#284)` 
Then you can rebase and add it to the 3.10.2 bug fixes to include it in 3.10.2

2023-05-01 17:25 UTC, mambelli commented on factory/tools/manual_glidein_submit.py
> +            entry.log.warning(
`entry` is not defined. I think it should be `logging.warning(`

2023-05-29 21:06 UTC, mambelli commented
Please rebase the PR to avoid conflicts.
And the CHANGELOG.md first section usually is copied from the bottom template and titled "Changes Since Last Release" unless a release is cut.

2023-07-31 10:05 UTC, mmascher commented
Rebased and conflicts resolved

2023-08-17 18:24 UTC, mambelli approved these changes

2023-08-17 18:25 UTC, mambelli commented
Did a selective rebase to eliminate the pre-commit changes and fixed the CHANGELOG (additions were in old releases)

2023-08-17 18:26 UTC, merged