GitHub 89 37
glideinWMS/glideinwms pull request #91
Opened 2022-03-08 16:53 UTC by ddbox

backport issue 89 to branch_V3_7

2022-03-08 17:13 UTC, ddbox commented
Just noticed this from Steve

The glidein submitted ran and jobs matched to it, but it went held at the end of the job for reasons I have not yet figured out.
I don't think they are tied to the bug fix but would like to hold the ticket open until I figure that out.

2022-03-11 16:00 UTC, mambelli requested changes

2022-03-11 16:00 UTC, mambelli commented on unittests/unittest_utils.py
> +    """
See the main branch PR. Change this to google format

2022-03-16 18:59 UTC, mambelli approved these changes

2022-03-16 18:59 UTC, merged